### ISSUE TITLE
how can i run vmap on scannet datasets?

### ISSUE THREAD

**Issue by zhide730** [kxhit/vMAP#13]
after i run: python2 reader.py --filename ~/data/ScanNet/scannet/scans/scene0024_00/scene0024_00.sens --output_path ~/data/ScanNet/objnerf/ --export_depth_images --export_color_images --export_poses --export_intrinsics, there are /color /depth /intrinsic /pose folders in the output_path ,but there is no instance-filt or label-filt folder in the output_path, which run vmap on scannet dataset needs,how to solve it hoping for your reply,thanks!

**Comment by AlbertHuyb** [comment]
@zhide730  Same question. How do you get the instance-filt and label-filt folders? Thanks!

**Comment by kxhit** [comment]
I think you will get all the data after extracting .sen files following ScanNet instructions. What did you get after running `python2 reader.py --filename ~/data/ScanNet/scannet/scans/scene0024_00/scene0024_00.sens --output_path ~/data/ScanNet/objnerf/ --export_depth_images --export_color_images --export_poses --export_intrinsics` in the readme?

**Comment by AlbertHuyb** [comment]
I have only `depth`, `color`, `pose` folders under the output directory.

**Comment by AlbertHuyb** [comment]
Oh I should download the zip files from Scannet website, including `*_2d-instance-filt.zip` and `_2d-label-filt.zip`.

**Comment by kxhit** [comment]
Maybe have a look at [ScanNet repo ](https://github.com/ScanNet/ScanNet#data-organization)

**Comment by AlbertHuyb** [comment]
It works after I download the zip files. Thanks for your help!
