### ISSUE TITLE
How to test on TUM-RGBD datasets

### ISSUE THREAD

**Issue by bilibilijin** [kxhit/vMAP#14]
Let me start by congratulating you for the great work and thanking you for the well-organized and easy-to-follow repo.

But I don't seem to see the part of the code that is tested on TUM-RGBD

I want to know how to run vmap on the TUM-RGBD dataset, if possible, can you give the relevant steps or detailed code? Would appreciate it if possible.

Looking forward to your reply as soon as possible！

**Comment by kxhit** [comment]
Hi, thanks for your interest in our work!

The related [issue](https://github.com/kxhit/vMAP/issues/8) might be helpful.

For TUM-RGBD evaluation, we run vMAP and [ORB-SLAM-ros-wrapper](https://github.com/thien94/orb_slam3_ros_wrapper) online by playing TUM-RGB-D rosbag. 

The suggested steps are as follows:
1. Set up ORB-SLAM and make sure vMAP can get the correct frame poses from it.
2. Run Instance Segmentation + 3D data association or simply run Video Segmentation e.g. [XMem](https://github.com/hkchengrex/XMem) to get associated object masks.
3. Prepare rgb, depth, mask, pose offline and run vMAP, or run vMAP online by running ORB-SLAM online via ROS.
4. I would suggest running iMAP mode or TSDF-Fusion first to check if the data is correct (e.g., intrinsics, camera pose, depth scale). 

Hope it helps!

**Comment by bilibilijin** [comment]
Ok I got the steps roughly, I'll keep trying to test it on TUB-RGBD！Thank you so much!
