### ISSUE TITLE
3D mesh vis

### ISSUE THREAD

**Issue by RTsama** [kxhit/vMAP#15]
Excuse me, when I run the Vmap code you provided, the 3D mesh vis window pops up and remains unresponsive

. Which other environments require configuration? Thank you very much! :)

**Comment by kxhit** [comment]
Hi @RTsama , this [param](https://github.com/kxhit/vMAP/blob/f3c4b937b1e236152af8028320b9cc2ded1967a8/configs/Replica/config_replica_room0_vMAP.json#LL64C10-L64C20) controls how frequent the 3D mesh is visualised. Please note that the training script is a single thread, thus the visualisation will block the training. You can implement a vis thread in parallel for continuous visualisation.

**Comment by RTsama** [comment]
Thank you @kxhit  for your patient answer. I have solved my problem. Good luck with your work:)
