### ISSUE TITLE
data generation for other replica scenes

### ISSUE THREAD

**Issue by Taekbum** [kxhit/vMAP#18]
Hello. I appreciate you sharing code of this impressive research.
I'm now interested in evaluating the performance of vMAP in different replica scenes, so I'd like to ask about the data generation process.
First, how were the trajectories for model training (trajectory 00) and novel view synthesis (trajectory 01) generated?
Second, how to obtain object-level meshes ? (to evaluate the 3D reconstruction performance at the object level) The original replica dataset seems to provides only scene-level meshes.
Thank you!

**Comment by kxhit** [comment]
Hi @Taekbum, you can send me your pose file via email and see if I can get it rendered correctly!

**Comment by Taekbum** [comment]
Thank you so much!

**Comment by kxhit** [comment]
Hi @Taekbum 
I just upload replica data generation scripts. Could you try and let me know if it works well? Cheers!

**Comment by Taekbum** [comment]
![Screenshot from 2023-06-19 20-25-21](https://github.com/kxhit/vMAP/assets/53718808/6e4430ca-827e-4458-ab7a-33b6883e618d)
Hi @kxhit , unfortunately not.
I tried, but segmentation fault occurred and the error message says some default files (e.g ./data/default.physics_config.json) is missing.

**Comment by Taekbum** [comment]
@kxhit It works well. Thank you!
