### ISSUE TITLE
Depth L1 results: Table C in Supplementary Material

### ISSUE THREAD

**Issue by abdulkarimatrash** [kxhit/vMAP#19]
Dear authors,

Thank you for sharing your outstanding work! 

I am wondering how can I replicate the Depth L1 results in Table C in the supplementary material. 

Any guidance would be highly appreciated.

Thanks in advance for your time in reading and responding to my question.

Regards,

**Comment by kxhit** [comment]
Hi, 
All 2D metrics are evaluated at scene-level. For the Depth L1 metric, we follow standard NeRF evaluation, calculating L1 distance between rendering depth and GT depth for a novel view. 
For vMAP's depth rendering, we first render depth within each object neural field and then combine all the object depths together by ranking the depth (small depth will replace the large depth, indicating occlusion among objects) to obtain a scene-level depth rendering image. To speed up object-level depth rendering, we do ray-box intersection AABB to reduce the number of rays to calculate.
