### ISSUE TITLE
Question about the Object Initialisation and Association

### ISSUE THREAD

**Issue by Runsong123** [kxhit/vMAP#20]
Dear Author,

Thanks for your great works.
I want to find the corresponding code for the 'Object Initialisation and Association part'. But I am confused since I couldn't find it. Could you please tell me the specific location?

![image](https://github.com/kxhit/vMAP/assets/39645074/02bc3fb4-73ee-4615-ac82-0539ed7b16d4)

Bests,
Runsong

**Comment by kxhit** [comment]
Hi, we didn't release this part of the code. For Replica, we use the associated object IDs from the dataset.

**Comment by Runsong123** [comment]
Got it. Thanks.
