### ISSUE TITLE
About object mesh.

### ISSUE THREAD

**Issue by zhaihongjia** [kxhit/vMAP#22]
How did you get the mesh for each object (for TSDF-Fusion and iMAP)?

**Comment by kxhit** [comment]
We use the GT bbox for each object and cut the global mesh to get the object-level mesh for iMAP as iMAP doesn't have object-level representation. For TSDF-Fusion, we use the object mask to build object-level reconstruction. Figure D in the appendix clearly shows what has been reconstructed at object level. Hope it makes sense.
