### ISSUE TITLE
How to get scene mesh rather than object mesh?

### ISSUE THREAD

**Issue by small-zeng** [kxhit/vMAP#23]
Thanks for your nice work.  When I run `python ./train.py --config ./configs/Replica/config_replica_room0_vMAP.json --logdir ./logs/vMAP/room0 --save_ckpt True`， I can get mesh of different objects, but the scene mesh as video is missing, How can I to get it?

**Comment by kxhit** [comment]
Hi @small-zeng The scene level mesh can be easily constructed by simply combining all object meshes together.

**Comment by small-zeng** [comment]
Thanks for your response, Can you tell me how to run the comannd to combine all object meshes together? I do not find it in the code.

> Hi @small-zeng The scene level mesh can be easily constructed by simply combining all object meshes together.

**Comment by kxhit** [comment]
`# Combine meshes into a single mesh
meshes_list = [mesh1, mesh2, ...]  # Replace with your mesh objects
combined_mesh = trimesh.util.concatenate(meshes_list)`

**Comment by small-zeng** [comment]
> `# Combine meshes into a single mesh meshes_list = [mesh1, mesh2, ...] # Replace with your mesh objects combined_mesh = trimesh.util.concatenate(meshes_list)`

Thank you, I will try it

**Comment by small-zeng** [comment]
I have obtained a combined mesh, but it is 2GB in size and is too large. My computer cannot open it in MeshLab. Is there a way to adjust the resolution of each object during training?

**Comment by kxhit** [comment]
You can definitely subsample the mesh at any time you want right? For example, when you combine the object meshes to a scene mesh you can do some subsample or when you do marching cube after training you can also set the resolution to control the size.
