### ISSUE TITLE
Question about ground-truth object mesh in Replica dataset

### ISSUE THREAD

**Issue by Pixie8888** [kxhit/vMAP#25]
Hi,

Thanks for releasing code! I have some question about the ground-truth object mesh in the replica dataset:

1.Line 27-28 in data_generation/extract_inst_obj.py, why does ``` sub_mesh_indices[object_id] ``` append twice? 
<img width="549" alt="image" src="https://github.com/kxhit/vMAP/assets/72333326/13268acf-4a77-4a3d-8791-833a8eab311e">

2. The ground-truth object mesh has holes due to occlusion. How can we faithfully evaluate the reconstructed object-level mesh on the occluded surface?
For example, there are holes on the sofa due to the pillows on top of it.
<img width="413" alt="image" src="https://github.com/kxhit/vMAP/assets/72333326/827e2231-481b-41bc-b0a0-cf5215b65e76">

**Comment by kxhit** [comment]
Hi, thanks for your interest!

1. Sorry, I can't really remember why. Does it work well without appending twice? If so, it might be a typo. I think the object-level mesh is still correct.
2. I tried to find the complete mesh at the object level, but this is the best object-level GT mesh I can get from the Replica Dataset by splitting the scene mesh. I didn't find a better dataset that both contains good/diverse object/scene level mesh and supports data rendering. Please let me know if I missed any good datasets.

**Comment by Pixie8888** [comment]
Thanks for your reply!
